Repository wecode-bootcamp-korea/23-1st-ggugit-backend, pull requests merged in 2021-08, with the labels that each got.

#1 [꾸깃] 모델링.4
  cookit/settings.py
  cookit/urls.py
  orders/__init__.py
  orders/admin.py
  orders/apps.py
  orders/migrations/__init__.py
  orders/models.py
  orders/tests.py
  orders/views.py
  products/__init__.py
  products/admin.py
  products/apps.py
  products/migrations/__init__.py
  products/models.py
  products/tests.py
  products/views.py
  users/__init__.py
  users/admin.py
  users/apps.py
  users/migrations/__init__.py
  users/models.py
  users/tests.py
  users/urls.py
  users/views.py
Labels: Status: 리뷰 요청

#2 [꾸깃] 회원가입 및 로그인
  cookit/settings.py
  cookit/urls.py
  orders/migrations/0001_initial.py
  orders/models.py
  products/migrations/0001_initial.py
  requirements.txt
  users/migrations/0001_initial.py
  users/urls.py
  users/views.py
Labels: Status: Accepted

#3 Add: Products views 작성.2
  .gitignore
  cookit/urls.py
  orders/migrations/0001_initial.py
  orders/models.py
  products/migrations/0001_initial.py
  products/models.py
  products/urls.py
  products/views.py
  users/migrations/0001_initial.py
  users/utils.py
  users/views.py
Labels: Status: Accepted

#4 [꾸깃] 상세페이지 구현
  .gitignore
  orders/views.py
  products/urls.py
  products/views.py
Labels: Status: Accepted

#6 [23기 김훈태] Add: 장바구니 삭제기능(DELETE)
  cookit/urls.py
  orders/urls.py
  orders/views.py
Labels: Status: Accepted

#5 [23기 장이주] Add : 장바구니 기능 추가, (CREATE, READ)
  orders/urls.py
  orders/views.py
Labels: Status: Accepted

#7 [23기 장이주] 모델링 수정, 데이터 추가
  orders/migrations/0001_initial.py
  orders/views.py
  products/migrations/0001_initial.py
  products/models.py
  products/views.py
  users/migrations/0001_initial.py
Labels: Status: 수정 요청

#8 [23기 장이주] 상품목록, 상품상세 API 데이터 수정
  orders/migrations/0001_initial.py
  products/migrations/0001_initial.py
  products/models.py
  products/urls.py
  products/views.py
  users/migrations/0001_initial.py
Labels: Status: 리뷰 요청

#9 [23기 장이주]장바구니 patch 추가, post 수정
  orders/urls.py
  orders/views.py
Labels: Status: 리뷰 요청

#10 [23기 김훈태] 메인페이지 이미지 배너 추가2
  orders/migrations/0001_initial.py
  products/migrations/0001_initial.py
  products/urls.py
  products/views.py
  users/migrations/0001_initial.py
Labels: Status: 리뷰 요청

#11 [23기 장이주] 검색 기능 추가
  products/urls.py
  products/views.py
Labels: Status: 리뷰 요청

#12 [23기 김훈태] Add: 장바구니 이미지 추가 및 id값 추가
  orders/views.py
  products/views.py
Labels: Status: 리뷰 요청
